services:
  - type: web
    name: ahmed-adly-portfolio
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 seo_server:app
    autoDeploy: true
